tasks:
  - name: aws-cli
  before:
    - name: Install AWS-CLI
      command: |
        cd ./workspace
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        aws --version
        rm -rf aws awscliv2.zip
