tasks:
  - name: utils
    before:
      - name: Install dependencies
        command: |
          sudo apt-get update && \
          sudo apt-get install -y tree ruby-full default-jdk jq

  - name: aws-cli
  before:
    - name: Install AWS-CLI
      command: |
        cd ./workspace
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        aws --version
        rm -rf aws awscliv2.zip
